LIlGG/halo-theme-sakura

- footer.ftl
- header.ftl
~~部分静态资源的版本有变动，但功能不受影响（目前仅在[我的网站](https://meow.mashiro.best)上测试过）~~
更新 `jqcloud` cdn 为 jsdelivr
> jqcloud:bootcdn→jsdelivr

- search.ftl
Fixes #34 
根据 主题中的 `分页模式` 设置来确定是否使用ajax分页。
测试页面: [测试](https://meow.mashiro.best/search?keyword=1)
> 搜索内容使用ajax分页

- languages/ja.yml
- settings.yaml
修复 #280 中的问题
ps: 工地日语，翻译得比较硬，不足还请见谅
> feat: 添加日语的语言文件

- languages/en.yml
- settings.yaml
> feat(post): 新增英文语言包 #283

- templates/layouts/post-nextprev.html
> 尝试修复next post / previous post 图片加载失败

- templates/error/404.html
增加适配 404 错误页面。404 页面搜索功能等待基于路由的搜索功能完成后适配。
> Halo 支持详见 https://github.com/halo-dev/halo/pull/2925
> feat: support 404 error page

- templates/layout.html
- templates/module/home/index.html
Fixes #370 
```
解决下拉箭头无法通过配置关闭的问题
```
> fix: 解决下拉箭头总会开启的问题

- templates/module/sidebar/mobile-sidebar.html
Fixes #364 
```release-note
将移动端头像由登录用户头像改为站点 LOGO
```
> pref: 将移动端头像改为站点 LOGO

- templates/module/header/user.html
Fixes #400 
```release-note
修复个人资料点击后为 admin 的问题
```
> fix: 修复个人资料点击后为 admin 的问题

- src/css/common/components/page-header.css
Fixes #360 
```release-note
修复背景图滤镜未生效的问题
```
> fix: 修复背景图滤镜未生效的问题

- settings.yaml
- templates/module/header/brand.html
> 添加站点标题是否使用Logo的优先级选项 (#372)

- .github/workflows/build.yaml
/kind improvement
升级  github action 内的组件版本。使用 cache 的新语法。
Fixes #429 
```release-note
None
```
> chore: 升级 workflows,使用新语法

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
/kind feature
增加 husky，用于在 git 提交前执行一遍 build。防止提交时遗忘。
```release-note
None
```
> feat: 添加 husky 用于在提交前执行一次 build

- templates/module/head/fonts.html
/kind improvement
移除字体文件中的 `Noto Serif` 字体。
移除字体文件中的拉丁文语言。（但下载的字体中可能包含）
```release-note
移除不必要的字体，优化字体文件加载数量
```
> 优化字体文件加载数量,移除不必要的字体及拉丁文相关

- theme.yaml
> chore: release-2.1.0

- settings.yaml
- templates/macro/content-thumb.html
- templates/macro/content.html
- templates/macro/page-header.html
- templates/module/post-pagination.html
> feat(random_image): customize resource identifier param name

- .all-contributorsrc
- README.md
添加 [all-contributors](https://github.com/all-contributors/all-contributors) 至项目中。
> ci: add all-contributors bot

- README.md
- package.json
- pnpm-lock.yaml
添加 all-contributors-cli 并生成 README。
> chore: add all-contributors-cli

- .github/workflows/build.yaml
see: https://github.com/pnpm/action-setup/issues/135
> ci: solve the problem of pnpm action v2 error

- settings.yaml
- templates/module/home/img_box.html
- templates/module/sidebar/mobile-sidebar.html
> feat: add properties to customize mainScreen self intro

- templates/module/sharelike.html
/kind bug
解决微信扫码分享的链接没有外部访问地址的问题。
Fixes #557 
```release-note
解决微信扫码分享的链接没有外部访问地址的问题。
```
> fix: solve the problem of incomplete wechat sharing links

- templates/module/home/img_box.html
自定义主屏自我介绍在没有添加任何sns链接的时候无法显示
参考：https://github.com/LIlGG/halo-theme-sakura/issues/562#issuecomment-2570034064
> fix: Customize mainScreen self intro display issue

- src/languages/en.json
- src/languages/ja.json
- src/languages/zh.json
- src/page/post.ts
> fix: update reminder messages for post length in multiple languages

- src/page/tags.ts
- templates/tags.html
修复开启开启 PJAX 局部刷新时点击标签云不触发pjax局部刷新问题。
https://github.com/user-attachments/assets/6d32ff65-e9b9-49cd-a55d-c6c3e4b2853c
> fix: 修复开启PJAX局部刷新标签云跳转局部刷新不生效问题

- settings.yaml
- templates/macro/content-post.html
feat：#167 
- 可自定义尾部文字
- 可自定义尾部图标（iconify图标）
- 可自定义尾部图标颜色
> feat: 自定义文章尾部
